version: '3.8'

services:
  case-api:
    build: .
    container_name: case-api
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URL: mongodb://root:example@mongo/
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo-case-api
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_volume:/data/db

volumes:
  mongodb_volume: